# Generated by Django 3.1 on 2020-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidityreading',
            name='reading_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='reading_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
