# Generated by Django 3.1 on 2020-08-28 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200828_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidityreading',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.device'),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='humidityreading',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
