# Generated by Django 3.1 on 2020-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200828_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityreading',
            name='reading_type',
        ),
        migrations.RemoveField(
            model_name='temperaturereading',
            name='reading_type',
        ),
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humidityreading',
            name='reading',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='reading',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
